language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
# command to run tests
before_script:
  - echo -e "machine github.com\n  login $TRAVIS_API_TOKEN" > ~/.netrc
  - mkdir repo
  - mkdir downloads
  - cp -r ./.git ./repo
script:
  - cd repo && python ../main.py
branches:
  only:
    - master
