language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
  - echo -e "machine github.com\n  login $TRAVIS_API_TOKEN" > ~/.netrc
  - mkdir repo
  - cp -r ./.git ./repo
  - python -m pygit --m ${TRAVIS_BUILD_DIR} -v 1
script:
  - python main.py
services:
  - docker
branches:
  only:
    - master
